# Generated by Django 3.2 on 2021-05-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_notebook_smatrphone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Smatrphone',
            new_name='Smartphone',
        ),
    ]
