# Generated by Django 3.2 on 2021-05-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_smatrphone_smartphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='frontal_cam_mp',
            field=models.CharField(max_length=255, verbose_name='Фронтальная камера (МП)'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='main_cam_mp',
            field=models.CharField(max_length=255, verbose_name='Камера (МП)'),
        ),
    ]
