# Generated by Django 3.2 on 2021-06-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210608_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_data',
            new_name='order_date',
        ),
    ]
